<?php
session_start(); // Start the session at the very beginning
require_once 'db_connect.php'; // Include your database connection

$error_message = '';

// If admin is already logged in, redirect to dashboard
if (isset($_SESSION['admin_logged_in']) && $_SESSION['admin_logged_in'] === true) {
    header("Location: admin_dashboard.php");
    exit;
}

if ($_SERVER["REQUEST_METHOD"] == "POST") {
    // CORRECTED: Match HTML form input names
    $username_input = trim($_POST['username'] ?? ''); // Changed from 'admin_username'
    $password_input = trim($_POST['password'] ?? ''); // Changed from 'admin_password'

    if (empty($username_input) || empty($password_input)) {
        $error_message = "Username and password are required.";
    } else {
        try {
            // Ensure column names in SELECT match your database table structure (e.g., admin_username, admin_password)
            // The database screenshot showed 'admin_username' and 'admin_password' as column names.
            $stmt = $pdo->prepare("SELECT id, admin_username, admin_password FROM admins WHERE admin_username = ?");
            $stmt->execute([$username_input]);
            $admin = $stmt->fetch(PDO::FETCH_ASSOC); // Fetch as an associative array

            // $admin['admin_password'] from DB MUST be a HASH generated by password_hash()
            if ($admin && password_verify($password_input, $admin['admin_password'])) {
                // Password is correct
                $_SESSION['admin_logged_in'] = true;
                $_SESSION['admin_id'] = $admin['id'];
                $_SESSION['admin_username'] = $admin['admin_username']; // Use the username from the DB
                
                // Regenerate session ID for security
                session_regenerate_id(true); 

                header("Location: admin-dashboard.php"); // Redirect to admin dashboard
                exit;
            } else {
                $error_message = "Invalid username or password.";
                // For debugging (REMOVE FOR PRODUCTION):
                // if ($admin) {
                //     error_log("Admin Login Debug: User found, password_verify failed. DB Hash: " . $admin['admin_password']);
                // } else {
                //     error_log("Admin Login Debug: User not found for username: " . $username_input);
                // }
            }
        } catch (PDOException $e) {
            error_log("Admin Login Database Error: " . $e->getMessage());
            $error_message = "An error occurred with the database. Please try again later.";
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--FONTS-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Genos:ital,wght@0,100..900;1,100..900&family=Orbitron:wght@400..900&family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <!---->
    <!--STYLE SHEETS-->
    <link rel="stylesheet" href="css/footer.css">
    <link rel="stylesheet" href="css/navbar.css">
    <link rel="stylesheet" href="css/style.css">
    <!---->
    <title>Chasing Completion - Admin Login</title>
</head>
<body class="admin-body">
    <?php include 'navbar.php' // Make sure navbar.php also calls session_start() if it needs session data ?>
    <div class="admin-login-container">
            <h2>Admin Login</h2>
        <div class="admin-login-box">
            <?php if (!empty($error_message)): ?>
                <p class="error-message" style="color: red; text-align: center; padding-bottom: 10px;"><?php echo htmlspecialchars($error_message); ?></p>
            <?php endif; ?>
            <form method="POST" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>">
                <div class="input-field">
                    <label for="username">Username</label>
                    <input type="text" id="username" name="username" required value="<?php echo isset($_POST['username']) ? htmlspecialchars($_POST['username']) : ''; ?>">
                </div>

                <div class="input-field">
                    <label for="password">Password</label>
                    <input type="password" id="password" name="password" required>
                </div>

                <button type="submit">Login</button>
            </form>
        </div>
    </div>
    <?php include 'footer.php'?>
</body>
<script src="javascript/bar-menu.js"></script>
</html>